# Generated by Django 5.1.1 on 2024-09-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruposDeInvestigacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('grupo_investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruposDeInvestigacion.grupoinvestigacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.categoria')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categorias',
            field=models.ManyToManyField(through='publicaciones.PublicacionCategoria', to='publicaciones.categoria'),
        ),
        migrations.CreateModel(
            name='PublicacionPalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.palabraclave')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='palabras_clave',
            field=models.ManyToManyField(through='publicaciones.PublicacionPalabraClave', to='publicaciones.palabraclave'),
        ),
        migrations.CreateModel(
            name='PublicacionTipoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion')),
                ('tipo_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.tipopublicacion')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipos_publicacion',
            field=models.ManyToManyField(through='publicaciones.PublicacionTipoPublicacion', to='publicaciones.tipopublicacion'),
        ),
    ]
