# Generated by Django 5.0.9 on 2024-10-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='publicaciones/pdf/'),
        ),
    ]
