# Generated by Django 5.0.9 on 2024-10-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_remove_publicacion_categorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='tipos_publicacion',
        ),
        migrations.DeleteModel(
            name='PublicacionTipoPublicacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipos_publicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.tipopublicacion'),
        ),
    ]
