# Generated by Django 5.0.9 on 2024-10-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipousuario',
            old_name='nombre_tipo',
            new_name='name',
        ),
    ]
