# Generated by Django 5.0.9 on 2024-10-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_nombre_tipo_tipousuario_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='programa',
            new_name='program',
        ),
    ]
