# Generated by Django 5.0.9 on 2024-10-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programa',
            old_name='nombre_programa',
            new_name='program_name',
        ),
    ]
